[debug] hft引擎on_getbars参数不一致
在on_stra_get_barL162行中调用ctx.on_getbars(bytes.decode(stdCode), period, bars)，由于hft与cta 等引擎在on_getbars中的参数不一致，因此会报如下错误
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "D:\ProgramFiles\anaconda3\envs\quant\lib\site-packages\wtpy\wrapper\WtWrapper.py", line 162, in 
on_stra_get_bar
    ctx.on_getbars(bytes.decode(stdCode), period, bars)
TypeError: on_getbars() missing 1 required positional argument: 'isLast'
```